### ISSUE TITLE
Some problem about testing parameters

### ISSUE THREAD

**Issue by lzhnb** [yanxp/MetaR-CNN#7]
The first problem is the spelling mistake in example command which is **'fisrt'** , I put it in pull requests.

And the other is the lack of parameter ```--phase```

when i run your example, it calls:
```sh
Traceback (most recent call last):
  File "test_metarcnn.py", line 187, in <module>
    mean_class_attentions = pickle.load(open(os.path.join('attentions',str(args.phase) + '_shots_' + str(args.shots) + '_mean_class_attentions.pkl'), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'attentions/1_shots_10_mean_class_attentions.pkl'
```
And it should be 'attentions/2_shots_10_mean_class_attentions.pkl', the first number depends on ```--phase``` ,now i add ```--phase 2``` and it works.

**Comment by yanxp** [comment]
Thanks, i wll update it.
