### ISSUE TITLE
Confusion about coco split

### ISSUE THREAD

**Issue by lzhnb** [yanxp/MetaR-CNN#8]
In your paper, the tasks contain **MS COCO to PASCAL**.

And i'm curious about the classes-split of this task:

1. Choosed classes from voc (20 classes) as novel classes and let rest classes(60 classes) be the bases classes. 
> This is my first comprehension of this task after reading paper

2. Choosed classes from your split_file (three txt - 5 classes) as novel classes and the rest classes in voc classes (15 classes) as base classes. 
> I've change your train example and train successfully in coco dataset, i find the base and novel classes also depends on the ```meta_type``` which splits the voc_classes into 15 base classes and 5 novel classes

Thanks

**Comment by yanxp** [comment]
Yes, It 's right.

**Comment by lzhnb** [comment]
So, the second comprehension is right?

**Comment by zb1439** [comment]
Samely curious about this issue! I'm not clear with class split with COCO dataset (is it 60-20 split as previous work on few shot detection like LSTD or using VOC classes only with 15-5 split) ? In addition, could you please release your interface for COCO dataset training? Thx and looking forward to reply.
